# configurations for backend pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipyard-backend-configmap
  namespace: dev
data:
  DATABASE_DRIVER: "postgres"
  DATABASE_HOST: "shipyard-db-service"
  DATABASE_PORT: "5432"
  DATABASE_SSLMODE: "disable"
  DATABASE_NAME: "dbconfigmapdb"
  DATABASE_USER: "dbconfigmapuser"
  DATABASE_PASSWORD: "dbconfigmappass"

  config.hcl: |
    api_slug = "shipyard"
    api_addr = ":8080"
    idp_addr = ":8081"
    metric_addr = ":8082"
    graceful_shutdown_timeout_sec = 5
    write_timeout_sec = 15
    read_timeout_sec = 15
    idle_timeout_sec = 15
    idp_password_salt = "00000"
    idp_client_id = "idp_client_id"
    idp_client_secret = "idp_client_secret"
    loglevel = "debug"
    developer_mode = true
    client_hosts = ["http://shipyard.tech"]
    public_api_url = "http://api.shipyard.tech"
    public_idp_url = "http://idp.shipyard.tech"

---

# template to define backend pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipyard-backend-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: shipyard-backend
      #tier: backend
  template:
    metadata:
      labels:
        app: shipyard-backend
        #tier: backend
    spec:
      # to copy minikube hosts /etc/hosts to each pod (so that
      # idp.shipyard.tech can be resolved from within the pods)
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: shipyard-backend-docker
        image: "samolds/shipyard-api:latest"
        command: ["/usr/local/bin/entrypoint.sh", "/usr/local/bin/shipyard"]
        args: ["--configs", "/etc/config/shipyard_backend/config.hcl,/etc/config/shipyard_backend/secrets.hcl"]
        ports:
        - containerPort: 8080
          name: api
        - containerPort: 8081
          name: idp
        - containerPort: 8082
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 2
            memory: 200Mi
        livenessProbe: # TODO(sam): review this
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 200
          periodSeconds: 30
          timeoutSeconds: 15
        readinessProbe: # TODO(sam): review this
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
        envFrom:
        - configMapRef:
            name: shipyard-backend-configmap
        - secretRef:
            name: shipyard-backend-secret
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: shipyard-backend-config
          mountPath: /etc/config/shipyard_backend
          readOnly: true
      volumes:
      - name: shipyard-backend-config
        projected:
          sources:
          - configMap:
              name: shipyard-backend-configmap
          - secret:
              name: shipyard-backend-secret
      initContainers:
      - name: shipyard-backend-init-db
        image: busybox
        command: ['sh', '-c', 'until nc -z shipyard-db-service 5432; do echo waiting for db; sleep 2; done;']
  # shouldn't be necessary with hpa
  #replicas: 3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: # TODO(sam): review this
      maxSurge: 3
      maxUnavailable: 0

---

# abstraction to expose backend pods
apiVersion: v1
kind: Service
metadata:
  name: shipyard-backend-service
  namespace: dev
spec:
  selector:
    app: shipyard-backend
  type: LoadBalancer
  ports:
  - name: api
    port: 8000 # the exposed port picked up by the ingress
    targetPort: 8080 # containerPort. where the container is listening
    protocol: TCP
  - name: idp
    port: 8001
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: 8002
    targetPort: 8082
    protocol: TCP


## unavailable with minikube
#---
#
## service to dynamically scale backend pods
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: shipyard-backend-autoscaler
#  namespace: dev
#spec:
#  maxReplicas: 3
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: shipyard-backend-deployment
#  targetCPUUtilizationPercentage: 90
