# a storage solution for the grafana pods
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shipyard-grafana-persistentvolume
  # persistentvolumes don't use namespace
  labels:
    using-name: shipyard-grafana
    using-namespace: dev
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/shipyard-grafana-data
  # irl, this would be "Retain". otherwise, what's the point of the stateful
  # set?! this will essentially `rm -rf /volume/*` on the host machine
  persistentVolumeReclaimPolicy: Delete

---

# an abstraction above the persistent volume that deployments can mount
# as volumes
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shipyard-grafana-persistentvolumeclaim
  namespace: dev
spec:
  selector:
    matchLabels:
      using-name: shipyard-grafana
      using-namespace: dev
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
