# ingress to route frontend and backend traffic
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: democart-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: democart.tech
    http:
      paths:
      # https://github.com/kubernetes/ingress-nginx/issues/5265#issuecomment-612680524
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: democart-frontend-service
            port:
              number: 3000
  - host: api.democart.tech
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: democart-backend-service
            port:
              number: 8000
  - host: idp.democart.tech
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: democart-backend-service
            port:
              number: 8001
  - host: prom.democart.tech
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: democart-prometheus-service
            port:
              number: 9000
  - host: grafana.democart.tech
    http:
      paths:
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: democart-grafana-service
            port:
              number: 5000
