apiVersion: v1
kind: Secret
metadata:
  name: shipyard-backend-secret
  namespace: dev
type: Opaque
stringData:
  DATABASE_NAME: shipyard
  DATABASE_USER: dbuser
  DATABASE_PASSWORD: dbpass

  secrets.hcl: |
    #exposed_url = "http://localhost:8080"
    #client_hosts = ["http://localhost:3000"]
    graceful_shutdown_timeout_sec = 5
    write_timeout_sec = 15
    read_timeout_sec = 15
    idle_timeout_sec = 15
    idp_password_salt = "00000"
    idp_client_id = "idp_client_id"
    idp_client_secret = "idp_client_secret"
    loglevel = "debug"
    developer_mode = true

---

apiVersion: v1
kind: Secret
metadata:
  name: shipyard-db-secret
  namespace: dev
type: Opaque
stringData:
  POSTGRES_DB: shipyard
  POSTGRES_USER: dbuser
  POSTGRES_PASSWORD: dbpass
