scrape_configs:
# monitors the prometheus server itself
#- job_name: "prometheus"
#  static_configs:
#  - targets: ["localhost:9090"]

- job_name: "shipyard_backend_metrics"
  metrics_path: "/metrics"
  scrape_interval: 1s # originally 5s
  static_configs:
  - targets: ["api:8082"]
